version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: laravel-app
    networks:
      - laravel-app

  laravel-app:
    build:
      context: ./php
    container_name: laravel-app
    volumes:
      - ./src/:/home/source/main
    # working_dir: /home/source/main
    networks:
      - laravel-app
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    container_name: laravel-nginx
    restart: always
    ports:
      - "9000:80"
    depends_on:
      - laravel-app
    volumes:
      - ./src/:/home/source/main
    networks:
      - laravel-app

networks:
  laravel-app:

volumes:
  mysql_data:
