version: "3.8"
networks:
  laravel-app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

services:
  nginx:
    container_name: laravel-nginx-container
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel-app

  mysql:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: my-app
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel-app

  php:
    build: .
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel-app

  adminer:
    container_name: adminer-container
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - laravel-app
