version: "3.8"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-container
    ports:
      - 5173:80

  nginx:
    image: nginx:alpine
    container_name: vue-nginx-container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - vue-app
